
version: '3.1'

services:
  ldap:
    image: osixia/openldap:latest
    container_name: ldap_server
    environment:
      LDAP_ORGANISATION: "SRS"
      LDAP_DOMAIN: "srs.com"
      LDAP_ADMIN_PASSWORD: "admin"
    ports:
      - "389:389"   # LDAP
      - "636:636"   # Secure LDAP
    volumes:
      - ldap_data:/var/lib/ldap       # Store LDAP database
      - ldap_config:/etc/ldap/slapd.d  # Store configuration
    restart: always

  phpldapadmin:
    image: osixia/phpldapadmin
    container_name: ldap_admin
    environment:
      - PHPLDAPADMIN_LDAP_HOSTS=ldap
      - PHPLDAPADMIN_HTTPS=false  # Allow HTTP access
      - PHPLDAPADMIN_TRUST_PROXY_SSL=true
      - PHPLDAPADMIN_LDAP_CLIENT_TLS=false
    ports:
      - "8080:80"  # Web UI access
    depends_on:
      - ldap
    restart: always

volumes:
  ldap_data:
    driver: local
  ldap_config:
    driver: local

